package com.example.countdowndays.ui.theme

import androidx.compose.ui.graphics.Color

// 浅色：柔和现代的紫蓝调，搭配暖色强调
val md_primary = Color(0xFF6750A4)
val md_onPrimary = Color(0xFFFFFFFF)
val md_primaryContainer = Color(0xFFEADDFF)
val md_onPrimaryContainer = Color(0xFF21005D)
val md_secondary = Color(0xFF625B71)
val md_onSecondary = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFFE8DEF8)
val md_onSecondaryContainer = Color(0xFF1D192B)
val md_tertiary = Color(0xFF7D5260)
val md_background = Color(0xFFFEF7FF)
val md_onBackground = Color(0xFF1D1B20)
val md_surface = Color(0xFFFEF7FF)
val md_onSurface = Color(0xFF1D1B20)
val md_surfaceVariant = Color(0xFFE7E0EC)
val md_onSurfaceVariant = Color(0xFF49454F)
val md_outline = Color(0xFF79747E)
val md_outlineVariant = Color(0xFFCAC4D0)
val md_error = Color(0xFFB3261E)
val md_surfaceContainer = Color(0xFFF3EDF7)
val md_surfaceContainerHigh = Color(0xFFECE6F0)

// 深色
val md_primary_dark = Color(0xFFD0BCFF)
val md_onPrimary_dark = Color(0xFF381E72)
val md_primaryContainer_dark = Color(0xFF4F378B)
val md_onPrimaryContainer_dark = Color(0xFFEADDFF)
val md_secondary_dark = Color(0xFFCCC2DC)
val md_onSecondary_dark = Color(0xFF332D41)
val md_secondaryContainer_dark = Color(0xFF4A4458)
val md_onSecondaryContainer_dark = Color(0xFFE8DEF8)
val md_tertiary_dark = Color(0xFFEFB8C8)
val md_background_dark = Color(0xFF141218)
val md_onBackground_dark = Color(0xFFE6E0E9)
val md_surface_dark = Color(0xFF141218)
val md_onSurface_dark = Color(0xFFE6E0E9)
val md_surfaceVariant_dark = Color(0xFF49454F)
val md_onSurfaceVariant_dark = Color(0xFFCAC4D0)
val md_outline_dark = Color(0xFF938F99)
val md_outlineVariant_dark = Color(0xFF49454F)
val md_error_dark = Color(0xFFF2B8B5)
val md_surfaceContainer_dark = Color(0xFF211F26)
val md_surfaceContainerHigh_dark = Color(0xFF2B2930)
